### ISSUE TITLE
support document metadata & cover extraction

### ISSUE THREAD

**Issue by petri** [collective/Products.OpenXml#2]
The scenario:

With openxmllib (PR 17) soon supporting cover image extraction, we could build a nice Dexterity "Document" content type that auto-populates the title, description & subject values with those of the source OpenXml document, and sets the cover page. All with a nice default view of course.

This would be nice for intranet/extranet applications, ie. when lots of office docs need to be uploaded and made easily accessible. 

Is it ok to add some support for that in this package? How should this be implemented? By an adapter for INamedFile that developers can use to build a content type & views? Some other way?

Of course, there are other kinds of documents for which similar functionality would be nice (say, PDF docs). So it might be better to implement (pluggable) generic support somewhere else and just have Products.OpenXML provide OpenXML-doc-specific plugin for that?

**Comment by mauritsvanrees** [comment]
This reminds me of https://github.com/collective/collective.documentviewer although that does not handle setting a title, but it splits a PDF (and apparently word docs too) into pages and makes image files of them.
Sounds useful.
If a title can be extracted by openxmllib, that might good to do in a new behavior, as alternative for the name from title and name from filename behaviors.

**Comment by petri** [comment]
@mauritsvanrees I was hoping I could piggyback on the name from title behavior, but perhaps the behavior does its magic before I set the title (in the event subscriber)...?

As a nice small bonus, I found out we can also extract page count; a nice thing to show together with file size.

**Comment by mauritsvanrees** [comment]
Ah, wait, now that you mention it, my idea would be of a title-from-file behavior. But yeah, that can probably be done in an event subscriber.

**Comment by djay** [comment]
@mauritsvanrees +1 we have a need for a title-from-file behaviour. So don't mind if you want to open source that :)

**Comment by petri** [comment]
[openxmllib](https://github.com/glenfant/openxmllib) is now able to extract MS Office OpenXML document cover, when available. PyPI release pending.

**Comment by petri** [comment]
I've merged support for  [collective.filemeta](https://github.com/collective/collective.filemeta.

I did not yet add any behaviors specifically for title-from-file, but that should be easy to add now as well. I am hoping to make a release first though.

**Comment by petri** [comment]
Since the just-released version 1.2.0, Products.OpenXml can now be used with collective.filemeta package to extract metadata from OpenXml files.
