### ISSUE TITLE
Release 1.2 with metadata extraction support

### ISSUE THREAD

**Issue by petri** [collective/Products.OpenXml#4]
Products.OpenXml now implements pluggable metadata (including cover image) extraction for [collective.filemeta](https://github.com/collective/collective.filemeta), or any other package wishing to use metadata from OpenXML documents. 

AFAIK, there are no changes to existing code and only non-breaking additions since last release so it should be safe to make a release.

@mauritsvanrees @tdesvenain @glenfant @djay Is there anything else I should consider or people to notify before making a new release of Products.OpenXml?

**Comment by petri** [comment]
Released.

**Comment by glenfant** [comment]
Great !
